### ISSUE TITLE
cp37 binary wheel missing for Windows

### ISSUE THREAD

**Issue by ben-edna** [benfred/py-cpp-demangle#1]
Hi Ben,

Thanks for the great tool! Simple cross-platform demangling from python without dependencies.
We would like to use this package, but as can be seen [on the files list in PyPi](https://pypi.org/project/cpp-demangle/#files), there are no Windows C-python 3.7 wheels available.

I think this is due to the version of `cibuildwheel` that is used in [appveyor.yml](https://github.com/benfred/py-cpp-demangle/blob/master/appveyor.yml#L24). Since version [0.9.3](https://github.com/joerick/cibuildwheel#093)  it has support for python 3.7 on Windows.

**Comment by benfred** [comment]
Thanks - glad this is coming in useful for you! 

  I've updated this to use the latest cibuildwheel and py03 just now - it's in v0.1.0. It should have wheels generated for 3.7 on windows now.

One thing I think I should call out here though is that this is just wrapping the [rust cpp_demangle crate](https://github.com/gimli-rs/cpp_demangle) - and while this works for symbols produced for almost every C++ compiler, the one notable exception is MSVC.  I mainly wrote this as a guide to writing python extensions in rust - for real windows usage you might want to look at something like [symbolic](https://github.com/getsentry/symbolic) or [mvsc-demangler-rust](https://github.com/mstange/msvc-demangler-rust).  Symbolic has it's own python bindings already even, and also handles demangling rust/objc/swift symbols too.

**Comment by ben-edna** [comment]
Perfect thanks! I see the wheels now indeed.

We use it in a cross-platform (windows/linux) embedded CI/CD setup (IAR compiler) and this was the only pure python tool (installation wise) I could find.
